### PR TITLE
[ Basic Case Management ] Use abc.ABC with Django Models

### LINKED ISSUE #3134: Try using abstract base class with Django model
There might be some issue trying to use `abc.ABC` with Django models, but let's try it (again).

> my reading of this is that you are guarding against this scenario:
> ```
> In [1]: class A:
>    ...:     # define a `bark()` method if you inherit from this
>    ...:     pass
>    ...:
> 
> In [2]: class B(A):
>    ...:     # i don't care
>    ...:     pass
>    ...:
> 
> In [3]: o = B()
> 
> In [4]: o.bark()
> ---------------------------------------------------------------------------
> AttributeError                            Traceback (most recent call last)
> <ipython-input-4-b8e702532450> in <module>
> ----> 1 o.bark()
> 
> AttributeError: 'B' object has no attribute 'bark'
> 
> In [5]: # oh no
> ```
> …by doing this instead:
> ```
> In [5]: class A:
>    ...:     # define a `bark()` method if you inherit from this
>    ...:     def bark(self):
>    ...:         raise NotImplementedError('bad programmer, bad!')
>    ...:
> 
> In [6]: class B(A):
>    ...:     # i don't care
>    ...:     pass
>    ...:
> 
> In [7]: o = B()
> 
> In [8]: o.bark()
> ---------------------------------------------------------------------------
> NotImplementedError                       Traceback (most recent call last)
> <ipython-input-8-b8e702532450> in <module>
> ----> 1 o.bark()
> 
> <ipython-input-5-a6e82e32ac05> in bark(self)
>       2     # define a `bark()` method if you inherit from this
>       3     def bark(self):
> ----> 4         raise NotImplementedError('bad programmer, bad!')
>       5
> 
> NotImplementedError: bad programmer, bad!
> ```
> 
> this is fine, and more palatable now that you've moved from a whole bunch of `NotImplementedError`s to reusable custom `AbstractPropertyError` and `AbstractMethodError` exceptions, but the whole exercise really doesn't strike me as necessary. if you're a programmer, the `AttributeError` is going to stop you in your tracks just as well as `NotImplementedError` or `Abstract…Error`.
> 
> i think we discussed ABC, and maybe there was a reason not to use it that i've forgotten, but its advantage is that it yells at you as soon as you try to instantiate a class that hasn't implemented the necessary methods:
> ```
> In [1]: import abc
> 
> In [2]: class A(abc.ABC):
>    ...:     @abc.abstractmethod
>    ...:     def bark(self):
>    ...:         print('i can do stuff, but you still have to implement this method in subclasses')
>    ...:
>    ...:     @property
>    ...:     @abc.abstractmethod
>    ...:     def tail(self):
>    ...:         pass
>    ...:
> 
> In [3]: class B(A):
>    ...:     pass
>    ...:
> 
> In [4]: o = B()
> ---------------------------------------------------------------------------
> TypeError                                 Traceback (most recent call last)
> <ipython-input-4-a1efe0b6b2c6> in <module>
> ----> 1 o = B()
> 
> TypeError: Can't instantiate abstract class B with abstract methods bark, tail
> ```
> 
> docs for the combination of `@property` with `@abstractmethod`: https://docs.python.org/3/library/abc.html#abc.abstractproperty
> 
> _Originally posted by @jnm in https://github.com/kobotoolbox/kpi/pull/2537#discussion_r613763570_

### PR DESCRIPTION
**Pull request by noliveleger**
## Checklist

1. [x] If you've added code that should be tested, add tests
2. [ ] If you've changed APIs, update (or create!) the documentation
3. [x] Ensure the tests pass
4. [x] Make sure that your code lints and that you've followed [our coding style](https://github.com/kobotoolbox/kpi/blob/master/CONTRIBUTING.md)
5. [x] Write a description of your work suitable for publishing on [our forum](https://community.kobotoolbox.org/tag/release-notes)
6. [x] Mention any related issues in this repository (as #ISSUE) and in other repositories (as kobotoolbox/other#ISSUE)

## Description

3 new interfaces have been created previously: `OpenRosaFormListInterface`, `OpenRosaManifestInterface`, `SyncBackendMediaInterface`. These classes are supposed to be abstract classes. 
Abstract class are support by python3 thank you to `abc.ABC` meta class. 
This PR add supports to classes that inherit from `Django.db.models.Model` to inherit from these classes too without conflicts of the meta classes.

## Related issues

Part of #3057 
Fixes #3134

### CODE REVIEW

**Comment by jnm** [comment]
Note to self:
> maybe something akin to class Meta in django could provide the openrosa info [to avoid possible name collisions in the current interface approach]

https://github.com/kobotoolbox/kpi/pull/2537/files?file-filters%5B%5D=.py#r607504131

**Review by jnm — APPROVED** [review]
