### ISSUE TITLE
Try using abstract base class with Django model

### ISSUE THREAD

**Issue by jnm** [kobotoolbox/kpi#3134]
There might be some issue trying to use `abc.ABC` with Django models, but let's try it (again).

> my reading of this is that you are guarding against this scenario:
> ```
> In [1]: class A:
>    ...:     # define a `bark()` method if you inherit from this
>    ...:     pass
>    ...:
> 
> In [2]: class B(A):
>    ...:     # i don't care
>    ...:     pass
>    ...:
> 
> In [3]: o = B()
> 
> In [4]: o.bark()
> ---------------------------------------------------------------------------
> AttributeError                            Traceback (most recent call last)
> <ipython-input-4-b8e702532450> in <module>
> ----> 1 o.bark()
> 
> AttributeError: 'B' object has no attribute 'bark'
> 
> In [5]: # oh no
> ```
> …by doing this instead:
> ```
> In [5]: class A:
>    ...:     # define a `bark()` method if you inherit from this
>    ...:     def bark(self):
>    ...:         raise NotImplementedError('bad programmer, bad!')
>    ...:
> 
> In [6]: class B(A):
>    ...:     # i don't care
>    ...:     pass
>    ...:
> 
> In [7]: o = B()
> 
> In [8]: o.bark()
> ---------------------------------------------------------------------------
> NotImplementedError                       Traceback (most recent call last)
> <ipython-input-8-b8e702532450> in <module>
> ----> 1 o.bark()
> 
> <ipython-input-5-a6e82e32ac05> in bark(self)
>       2     # define a `bark()` method if you inherit from this
>       3     def bark(self):
> ----> 4         raise NotImplementedError('bad programmer, bad!')
>       5
> 
> NotImplementedError: bad programmer, bad!
> ```
> 
> this is fine, and more palatable now that you've moved from a whole bunch of `NotImplementedError`s to reusable custom `AbstractPropertyError` and `AbstractMethodError` exceptions, but the whole exercise really doesn't strike me as necessary. if you're a programmer, the `AttributeError` is going to stop you in your tracks just as well as `NotImplementedError` or `Abstract…Error`.
> 
> i think we discussed ABC, and maybe there was a reason not to use it that i've forgotten, but its advantage is that it yells at you as soon as you try to instantiate a class that hasn't implemented the necessary methods:
> ```
> In [1]: import abc
> 
> In [2]: class A(abc.ABC):
>    ...:     @abc.abstractmethod
>    ...:     def bark(self):
>    ...:         print('i can do stuff, but you still have to implement this method in subclasses')
>    ...:
>    ...:     @property
>    ...:     @abc.abstractmethod
>    ...:     def tail(self):
>    ...:         pass
>    ...:
> 
> In [3]: class B(A):
>    ...:     pass
>    ...:
> 
> In [4]: o = B()
> ---------------------------------------------------------------------------
> TypeError                                 Traceback (most recent call last)
> <ipython-input-4-a1efe0b6b2c6> in <module>
> ----> 1 o = B()
> 
> TypeError: Can't instantiate abstract class B with abstract methods bark, tail
> ```
> 
> docs for the combination of `@property` with `@abstractmethod`: https://docs.python.org/3/library/abc.html#abc.abstractproperty
> 
> _Originally posted by @jnm in https://github.com/kobotoolbox/kpi/pull/2537#discussion_r613763570_
